---
service: tannisDynamoDBStreamsLambda
frameworkVersion: '2'
provider:
  name: aws
  stage: prod
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: ap-south-1
  timeout: 10
  logRetentionInDays: 1
  iam:
    role: arn:aws:iam::502860870433:role/service-role/test-role-elybze7y
  vpc:
    securityGroupIds:
      - sg-0749bdf075ecccb19
    subnetIds:
      - subnet-0e14a634124b0f965
      - subnet-08b504261a6d7b39b

functions:
  compute:
    handler: streamProcessor.handler
    events:
      - stream:
          type: dynamodb
          arn: arn:aws:dynamodb:ap-south-1:502860870433:table/tannisUsers/stream/2021-09-02T05:25:32.757

plugins:
  - serverless-plugin-typescript

package:
  patterns:
    - '!.git/**'
    - '!.serverless/**'
    - '!.gitignore'
    - '!LICENSE'
    - '!README.md'
    - '!serverless.yml'
    - '!package-lock.json'
